name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      # encounter strange race condition when running those mock tests on github
      # disable them and do mock tests locally for now

      # - name: Run unit tests
      #   run: clojure -M:test -m cognitect.test-runner -e :mock

      # - name: Run basic mock test
      #   run: clojure -M:test -m cognitect.test-runner -d test/alligator/mock/basic/

      # - name: Run multiserver mock test
      #   run: clojure -M:test -m cognitect.test-runner -d test/alligator/mock/multiservers/

      # - name: Run diagnostic mock test
      #   run: clojure -M:test -m cognitect.test-runner -d test/alligator/mock/diagnostics/

      # - name: Run code-action mock test
      #   run: clojure -M:test -m cognitect.test-runner -d test/alligator/mock/code-actions/
